# Generated by Django 5.2.3 on 2025-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payments/"),
        ),
    ]
